### ISSUE TITLE
Invariant Violation: WebView 

### ISSUE THREAD

**Issue by sandeep-webvillee** [cloudipsp/react-native-cloudipsp#10]
Invariant Violation: WebView has been removed from React Native. It can now be installed and imported from 'react-native-webview' instead of 'react-native'. See https://github.com/react-native-community/react-native-webview

**Comment by berehovyi** [comment]
Fixed in version 0.4.0 .

**Comment by sailywebvillee** [comment]
Hello @vberegovoy  I am still getting the old version for the library that is "0.3.0" in place of new version mentioned by you. So can you please help me with this issue & getting the same error that is  - Invariant Violation: WebView has been removed from React Native. It can now be installed and imported from 'react-native-webview' instead of 'react-native'. See https://github.com/react-native-community/react-native-webview
